spring.application.name=Schedule_Project

spring.datasource.url=jdbc:mysql://localhost:3306/schedule_list
spring.datasource.username=yeang
spring.datasource.password=y46t*7*wi13hj
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
